### ISSUE TITLE
Two Separate Linksys Velop Mesh

### ISSUE THREAD

**Issue by aAbdman** [uvjim/linksys_velop#141]
Hello

Is it possible to have two separate linksys Velop's connected to HA?

I have two Linksys Velop networks, one for IoT and the other for regular internet use.
So I want to be able to connect both of them to Home Assistant if it is possible.

Thanks

**Comment by uvjim** [comment]
Hi. I actually stopped this from happening in `2022.2.3`. The reason was around the services, they wouldn't know which mesh to target for the action and it was causing issues.

**Comment by uvjim** [comment]
I've had a look and I might be able to accommodate this actually. It'll take me a little bit of time to update the services and do some testing.

I'll keep you posted.

**Comment by aAbdman** [comment]
Thank you very much
Really appreciate you taking the time for this.

**Comment by uvjim** [comment]
I think it's mostly done now. I need to adjust the event that's raised when a brand new device is found... It'll probably need to to tell you which mesh the device was found on.

**Comment by aAbdman** [comment]
Sounds great
would be happy to help in testing if you wish.

**Comment by uvjim** [comment]
Funny you mention that...  I've just pushed `2022.3.4b0`.  If you are using HACS you'll need to tell it to look for beta versions.  Could you test this please and see if everything still works and the new things work as you expect?

I still have some testing to do re: older versions of HASS but this will be a start.

**Comment by aAbdman** [comment]
Sure, Will do and get back to you....

**Comment by aAbdman** [comment]
Hi
I installed the new beta.
Everything looks good and stable until now. I will keep testing for the next 24 hours and update you of any issues.
Really appreciate your work.
Many thanks

**Comment by uvjim** [comment]
Just for clarity... HASS allows you to rename the instance names and you can also rename the Mesh devices if that makes life any easier for you.

**Comment by aAbdman** [comment]
Hello @uvjim uvjim
Everything looks good and satiable.
I am using my two Mesh networks as a bridge mood both connected to a pfSense firewall.
As a start the HA didn't discover any New mesh system (maybe do to my network structure and fire walls), So I had to add the integration manually which did the job.
Over the night one of my Nodes were unplugged accidentally, after plugging it back in the morning a new discovery messages in HA informed me of a new device discovery.
Finally, the integration works really well.

Thank you for the integration, your efforts and support.
cheers

**Comment by uvjim** [comment]
Brilliant.  That's good news.  I've got a pending change to do for the upcoming `2022.4` release of HASS so I'll do a release after the first beta comes out and I can test against that.  You'll notice that the minimum version of HASS supported will now be `2021.12.0` so hopefully you're running something newer.

**Comment by aAbdman** [comment]
Sounds great, can't wait.
Yes, I am running the latest update (I always do:))

**Comment by uvjim** [comment]
I've released this now so it should be available in HACS without needing beta.
