### ISSUE TITLE
Linksys Velop: Reboot Node Service Not working

### ISSUE THREAD

**Issue by aAbdman** [uvjim/linksys_velop#230]
Hello

In the beta version [2022.8.1b0 and 2022.8.1b0] the (Linksys Velop: Reboot Node) in not woking anymore.

**Comment by uvjim** [comment]
Are there any errors in the logs at all?

**Comment by uvjim** [comment]
I know what the issue is. It's late here so I'll deal with it tomorrow.

**Comment by uvjim** [comment]
Should be fixed in #231

**Comment by aAbdman** [comment]
Yes, it works good now.
Thank you
