### ISSUE TITLE
Device only detected when connected to 5g and not on 2.4g

### ISSUE THREAD

**Issue by naijaping** [uvjim/linksys_velop#25]
Hi,

Thanks for this very useful addon, I have been using it for some days now and working well. I have three nodes in my house and my 5g is separated from 4g for stability . 

Unfortunately, when I go out and back home, if my phone automatically connect to 4g I will not be detected as home until i manually connect to 5g. 

I know this might be a missing setting or something. I was using ping before and never had this issue .

**Comment by naijaping** [comment]
@uvjim, sorry I mean 2.4G, yes the device was showing on the Linksys app as connected .   if  my device join 5G then am detected as home but when i join 2.4G am shown as away.

Thanks for your help

**Comment by uvjim** [comment]
Does the Linksys app show them as 2 different devices or a single one?

I haven't separated my radios so can move between them easily and haven't had any stability issues.

Are you able to turn on some debug logging for me and I'll see what I can find from there.
