### ISSUE TITLE
Entity pictures not showing on Card 3

### ISSUE THREAD

**Issue by hesspoint** [uvjim/linksys_velop#286]
I added the cards in my dashboard. Really cool.

I have one issue: The pictures for my router and satellite in card 3 don't show.

In the code it seems to look into the local i.e. www folder in the subfolder velop_nodes on my HA instance for pictures
```
getEntityPicture: |
            () => {
              if (states[vars['ID_ENTITY_PICTURE']]) {
                return states[vars['ID_ENTITY_PICTURE']].state
              } else {
                if (states[vars['ID_MODEL']]) {
                    return '/local/velop_nodes/' + states[vars['ID_MODEL']].state + '.png'
                }
              }
            }
```

However on my HA there is no velop_nodes folder in my www folder. Is that supposed to be created during setup in HACS? Or do I manually need to upload it there? If the later where can I get the images?

On and one other thing, not a bug but a questions: in card 2 there is that huge globe icon that should show if my router is connected to the internet or not. I would like to make that a tad smaller. I found where to change the color in the code but I could not find the part where I can set the icon size. Can you point me to that?

Thanks.

**Comment by uvjim** [comment]
> However on my HA there is no velop_nodes folder in my www folder. Is that supposed to be created during setup in HACS? Or do I manually need to upload it there? If the later where can I get the images?

You'll need to create the folder. I just used images that I found using a search engine.



> I would like to make that a tad smaller. I found where to change the color in the code but I could not find the part where I can set the icon size. Can you point me to that?

You should be able to look at the documentation for the [button-card](https://github.com/custom-cards/button-card) to look at options that the card offers.
