### ISSUE TITLE
Card 3 custom fields display

### ISSUE THREAD

**Issue by elykrk** [uvjim/linksys_velop#297]
Thank you for the great integration and the sample code for Lovelace! Great work!

I am having a display issue with card 3 and the display of the model, serial, and IP address information. See below:

<img width="391" alt="Screen Shot 2022-10-12 at 11 46 57 AM" src="https://user-images.githubusercontent.com/69878955/195423923-39e13a7c-1be6-49f4-b4d6-d3915e09a0eb.png">

I've tried to mess around with the margins in the sample code but was unsuccessful in fixing this. 

Thanks!

**Comment by uvjim** [comment]
Hi, I've seen this before... Seems to be a cache issue in the browser due to the way card-mod works. Not sure what browser you're using, but for me normally a CTRL+F5 or CTRL+R solves it. If you're using the mobile app then normally force closing it, and re-opening kicks it into life.

**Comment by elykrk** [comment]
Thanks for the quick reply. I cleared the cache on my Mac using Safari, Windows PC using Chrome, and in the mobile app and the issue still persists across all three browsers. 

Any other suggestions?

**Comment by elykrk** [comment]
I am. I'm not sure what resolved this but it might have had to do with my custom theme. Whatever it was I re-installed the theme, cleared the cache, and it now seems to be working. Thanks!

**Comment by elykrk** [comment]
This issue returned. After further research, it looks like it might be related to this card-mod issue with auto-entities:

https://github.com/thomasloven/lovelace-card-mod/issues/184

Others report that styling issues were resolved after removing the auto-entities sections within the yaml code but I have not yet tried this to confirm.

**Comment by uvjim** [comment]
`card-mod` isn't used in that part of the card. The styling there is all handled by `button-card`.

If you remove card 2 does the problem persist?

There could be an issue with the styling inside the folds because they could be subject to that issue linked.
