### ISSUE TITLE
Feature request: Service call to request “Channel Finder”

### ISSUE THREAD

**Issue by dredjohn21** [uvjim/linksys_velop#298]
I’ve noticed over time my Velop starts running into Wi-Fi issues and using Channel Finder (from Wi-Fi advanced settings) solves the problems.

If this service was accessible I could automate to run this automatically every week and hopefully eliminate the problems proactively.

**Comment by uvjim** [comment]
I've had a quick look and this should be possible,  Give me some time and I'll make it available.

**Comment by uvjim** [comment]
support added upstream in https://github.com/uvjim/pyvelop/pull/146

**Comment by dredjohn21** [comment]
> I've had a quick look and this should be possible, Give me some time and I'll make it available.

Wow that would be amazing - thank you!

**Comment by uvjim** [comment]
Should be added by #300.  It's available in this beta release: https://github.com/uvjim/linksys_velop/releases/tag/2022.10.2b0 which should be available in HACS.

I've implemented this as a `button` and `binary_sensor` combination.  The `button` will start the scan and the `binary_sensor` will turn on when a scan is in progress and off when it is finished.  I've updated the README to reflect this.

I haven't built a service for this, but you should be able to use the `button.press` service which is available by default in Home Assistant.

Hope that helps.

**Comment by dredjohn21** [comment]
You are amazing - works perfectly!  Will hopefully ensure these devices are always optimized. (Linksys should hire you!!!)

One note: I did notice after the scan there were some errors in the logs and it took maybe 5 minutes for the devices to be recognized by the integration.  If others see this thread, don’t bother restarting HAOS - hang in there and it’ll reconnect.  Just takes some time.  Works perfectly.

**Comment by uvjim** [comment]
Ooooo. I didn't see any errors in all of my testing. I did find that the 2 nodes I have that were using a wireless backhaul would drop and come back again (seems to be normal behaviour).

What are the errors? If you could send them over (maybe a separate issue), I'll see if I can track them down before I do a full release.

**Comment by dredjohn21** [comment]
Sure thing - I'll add new issue now (although to stress: it seemed to self-recover)
