### ISSUE TITLE
Pictures of nodes 

### ISSUE THREAD

**Issue by reefnl80** [uvjim/linksys_velop#308]
Good evening,

sorry to shoot this in as a issue but I cannot get it right. 

So I created the velop_node folder in www, but I cannot got the picture up and running. I have 4 whw03 nodes. Can somebody please help guide me in this. 

I love the intergration, but as cherry on the cake I also would this so I can start building a new dash.

**Comment by uvjim** [comment]
Hi, the folder should be called `velop_nodes` and the example cards look for the images in there based on the model number.  So in my case it looks like this: -

![image](https://user-images.githubusercontent.com/8431065/196045308-fa0955eb-4019-4141-a6d8-3fa953b999bb.png)

The model number you use should match the one in the model number sensor.

Hope that helps.

**Comment by reefnl80** [comment]
Good evening. Thank you very much for the response. Can you maybe share the whw01 file you have so I can rename it to whw03. Thanks in advanced Philippe Verstuurd vanaf mijn iPhoneOp 16 okt. 2022 om 17:57 heeft uvjim ***@***.***> het volgende geschreven:﻿
Hi, the folder should be called velop_nodes and the example cards look for the images in there based on the model number.  So in my case it looks like this: -

The model number you use should match the one in the model number sensor.
Hope that helps.

**Comment by uvjim** [comment]
![WHW01.png](https://user-images.githubusercontent.com/8431065/196046210-6e1d969c-9f90-4aaf-85d4-691368be0912.png)

**Comment by reefnl80** [comment]
Hi,

thanks for the prompt reply. 

Strange thing is a placed the picture in the folder, renamed the file to WHW03 , but he is not picked up, please see below screenshots. 
![3A5FCDF9-CA33-4662-ACB0-A48D93D5FEFA](https://user-images.githubusercontent.com/82978117/196046802-bacc3d1e-320e-4f1e-9a81-7a6999d146ad.jpeg)
![C831CFC5-387C-4FED-9F91-74F3E4707EC7](https://user-images.githubusercontent.com/82978117/196046807-9a324fe2-4e1d-4832-9575-9e9717a10cad.jpeg)

**Comment by uvjim** [comment]
You may need to force reload the browser to invalidate the cache.  If you hover over the image placeholder does it tell you which file it is looking for?  If not (I'm using Firefox) you could inspect the page and see which image it is looking for.  The following screenshot shows the inspection window in Firefox (yours might look different in another browser).

![image](https://user-images.githubusercontent.com/8431065/196047294-5ef91206-1de0-4073-a571-ec5f6af2653a.png)
