### ISSUE TITLE
Card Border

### ISSUE THREAD

**Issue by mschingel** [uvjim/linksys_velop#317]
![image](https://user-images.githubusercontent.com/109315303/199639223-eca39c0c-fe51-415c-993b-383dbe31bf92.png)

I really like the cards,  I just recently updated HA and noticed that there is now a border..  Probably has something to do with a card update but I don't know how to remove that border to revert it to how it used to look.

**Comment by uvjim** [comment]
I have this resolved locally and will push the changes to the README later.

**Comment by uvjim** [comment]
fixed in https://github.com/uvjim/linksys_velop/commit/b93032f497c9a50e181eb448fa98135561883177

**Comment by uvjim** [comment]
Would I be right in assuming that one of the names in the name column is long?

**Comment by mschingel** [comment]
Its possible but why are Both notes that contain the same devices show up good.  I forgot to add this behavior only shows in HA IOS App (Android untested) Using Chrome in RPI or just in general it does not.  Also the txt on the notes smushed.  

The Mesh Card has the narrow IP address issue in the first picture
The Node Card has the narrow smushed Serial model and IP in the second picture
-All in HA App in iOS View.  However the DNS Public IP etc in the Mesh card appear fine and the Connected Devices Appear fine in the Node Card but not in the Online Devices of the Mesh Card

![image](https://user-images.githubusercontent.com/109315303/199767464-6e766f01-f3a6-48f6-988c-35394bdcf673.png)

**Comment by mschingel** [comment]
Edit - This is the Chrome view on desktop.  The Node cards do have the smushed titles now.

![image](https://user-images.githubusercontent.com/109315303/199769780-34694bee-447a-4212-8ff1-d5d58b28a3c7.png)

**Comment by uvjim** [comment]
I have no iOS devices to test with I'm afraid but my guess is that it's something to do with the way the styles are applied.  When I was using these cards I occasionally had issues with the style on the Mesh and Node (main areas).  A forced reload (bypassing cache) typically solved it.

The tables in the node card have no special styling applied to them re: column widths so that should be calculated by the browser based on available space.

The devices tables for the mesh is set break the IP address rather than the name column.

**Comment by mschingel** [comment]
For the Mesh card, could you set the breaks identical to how you did it in the Node cards as they appear to be functioning as expected in iOS.  I will clear cache and try in desktop to see if it fixes the SN Model etc in the Node card.

**Comment by uvjim** [comment]
If you want to test if it helps you, you could try locally...

![image](https://user-images.githubusercontent.com/8431065/199774147-d30c0b7c-10be-40e5-8e8b-fc6915ee9866.png)

Thats where the code is when you edit the card...  You'll need to remove the word-break items or set them to "normal" (that's the default value for that property.

**Comment by mschingel** [comment]
Thank you, That fix it by removing word-break and break-all stuff.

**Comment by uvjim** [comment]
That's good. I think I put them there to cope with long addresses for IPv6 and names.

I don't actually have those issues here so couldn't really test properly. 

I've moved away from these cards now so am unlikely to make any more changes to them unless something is drastically wrong.
