### ISSUE TITLE
Help: Template for detecting online device

### ISSUE THREAD

**Issue by mschingel** [uvjim/linksys_velop#351]
Use Case:  Create an automation that alerts me when the Drive Way Camera is detected on the Correct Node being the Garage Node.  When it is Not I will then restart it via a smart Plug.

![image](https://user-images.githubusercontent.com/109315303/209215962-ab782aca-288e-46e9-b49e-0e3336c13b0e.png)

{{ is_state_attr('sensor.garage_velop_connected_devices',Name,Value) }}

Would the proper way to make this work be:

{{ is_state_attr('sensor.garage_velop_connected_devices','Garage-Drive-Way-Camera',True) }}   # This didnt work for me.

Name: being the Garage Drive Way Camera 

**Edit (uvjim): I've split the possible issue into another issue so that the two can be handled separately**

**Comment by uvjim** [comment]
Try the following, changing the details as necessary.

```
{{ "Driveway - Camera" in (state_attr("sensor.velop_utility_connected_devices", "devices") | map(attribute="name")) }}
```

**Comment by uvjim** [comment]
See #352 for the issue that's been split out

**Comment by uvjim** [comment]
#352 is now resolved

**Comment by mschingel** [comment]
> Try the following, changing the details as necessary.
> 
> ```
> {{ "Driveway - Camera" in (state_attr("sensor.velop_utility_connected_devices", "devices") | map(attribute="name")) }}
> ```

That worked. But I’m noticing every hour it somehow find the device on the wrong node. Think this has to do with Velop and nothing ca be done here. 

I’m considering switching my nodes to full bridge mode. Will the device card continue to show devices and names? I’m trying to get a more reliable network and figured I would try it but live these cards.  I know parental controls and advance features will not work in bridge mode. But I hope it picks up the name and my samba drive works.

**Comment by uvjim** [comment]
Has the device actually moved nodes? If so, does it believe it has a better connection?

You could try looking at this, I've never needed to play with these settings myself.

https://www.linksys.com/support-article?articleNum=316222

RE: what's missing in bridge mode... https://www.linksys.com/gb/support-article/?articleNum=243551#sf6

From what I've read in the forum post on HA for people using the integration, some are in bridge mode, so it seemingly works but I'm not sure if they're using the example cards or not.

**Comment by uvjim** [comment]
Oh, and the backhaul section of the example cards will break in the next release (as in, not be shown) because the sensor and attributes have all been split into their own sensors.

**Comment by mschingel** [comment]
Okay good to know on the backhaul. 

The device is connected to a child node but every hour I will get a notification it’s on the primary node when it’s not. 

Once I get the notification I immediacy check and it’s not on the primary node. I may need to somehow link it to a sensor and do a count grater than 2 within an hr.

**Comment by uvjim** [comment]
I have devices that occasionally move around the nodes. They don't seem to have problems with it. Sometimes connections are weaker than others but they eventually move back again.

That template would check if the device name is connected on the given node. I'm assuming that you would want the automation to trigger if it isn't connected to the node - you may have already tweaked it to do that.

There's a number of reasons it could move nodes. Assuming that the camera doesn't support steering it could be because: -

* The node you believe it should connect to drops for some reason
* The camera drops for some reason and when it comes back it connects to a different node believing the wi-fi strength to be better

This definitely doesn't sound like something that the integration can resolve but I guess if the automation is correctly determining that the camera is disconnecting from the node, then you could link it to something like a counter helper to track how many times it's disconnected and then react to that.

Shall I close this off for now?

**Comment by mschingel** [comment]
Yea, it can be closed but.

I upgraded the Velop FW's and did a Factory Reset to 3 Nodes.  Reset them up and only 2 of the nodes show in the card.  But all 3 are discovered in HA.  Any idea why that is?

**Comment by uvjim** [comment]
IIRC the filter for that card looks for `binary_sensors` that have an `entity_id` that ends in `_status` and has a `guest_network` attribute that is either `true` or `false`; but isn't the `mesh` one.

I have seen this mean a node isn't shown until it comes fully online and meets those criteria.

There's a better set of filters that can be used but I haven't updated those cards for a while, and `auto-entities` didn't have the features when I did the last updates.

**Comment by uvjim** [comment]
If you want to make the filter slightly better for getting the nodes on the card you could try this...


```yaml
filter:
  exclude:
     - entity_id: /\.mesh_/
  include:
     - integration: linksys_velop
       domain: binary_sensor
       entity_id: /_status$/
       attributes:
         device_class: connectivity
```

You may need to change the exclude to line up with the `entity_id` format that your mesh entities use.

**Comment by mschingel** [comment]
Dont think i had to change the entity id field.
