### ISSUE TITLE
Most of the feature didn't work for invalid credential

### ISSUE THREAD

**Issue by ChansoulTao** [uvjim/linksys_velop#376]
<img width="353" alt="Screenshot 2023-01-07 at 22 57 22" src="https://user-images.githubusercontent.com/97238684/211156873-4d0c42ae-4680-421d-81fd-2a26ada3e8a8.png">

Btw it also shows a notice that 

> The following integrations and platforms could not be set up:
> 
> [device_tracker](https://www.home-assistant.io/integrations/device_tracker) ([Show logs](http://homeassistant.local:8123/config/logs?filter=device_tracker))
> Please check your config and [logs](http://homeassistant.local:8123/config/logs).

here's the log
> Logger: homeassistant.setup
> Source: components/device_tracker/legacy.py:340 
> First occurred: 10:54:20 PM (1 occurrences) 
> Last logged: 10:54:20 PM
> 
> Error during setup of component device_tracker
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
>     result = await task
>   File "/usr/src/homeassistant/homeassistant/components/device_tracker/__init__.py", line 71, in async_setup
>     await async_setup_legacy_integration(hass, config)
>   File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 195, in async_setup_integration
>     legacy_platforms = await async_extract_config(hass, config)
>   File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 340, in async_extract_config
>     raise ValueError(
> ValueError: Unable to determine type for linksys_velop: None
>

**Comment by uvjim** [comment]
I don't think this is for my integration. How did you set your integration up? Was it after adding my repository to HACS?

**Comment by uvjim** [comment]
Hi, are you still having issues?  Did you check if it was with this integration?

**Comment by Judediting** [comment]
Hello,
I'm having the same issue :/
I put the ip address of my main node and the password of our wifi (even tried with smart wifi password) but it does't work. All the entities remain unavailable and if I tried one service like the speedtest I have "Invalid Credentials" error also.
I tried to downgrade from 2023.1 to 2022.12 but it doesn't change anything.

The only log files I have are the following : 

> Logger: aiohttp.server
> Source: custom_components/linksys_velop/diagnostics.py:53
> Integration: Linksys Velop ([documentation](https://github.com/uvjim/linksys_velop), [issues](https://github.com/uvjim/linksys_velop/issues))
> First occurred: 22:40:53 (2 occurrences)
> Last logged: 22:41:03
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
>     resp = await request_handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 264, in get
>     data = await info.device_diagnostics(hass, config_entry, device)
>   File "/config/custom_components/linksys_velop/diagnostics.py", line 96, in async_get_device_diagnostics
>     return await async_get_config_entry_diagnostics(hass, config_entry)
>   File "/config/custom_components/linksys_velop/diagnostics.py", line 53, in async_get_config_entry_diagnostics
>     "nodes": [node.__dict__ for node in nodes if nodes],
> TypeError: 'NoneType' object is not iterable

Do you know how I could handle this? I don't know what to try and didn't find any information or issue about it.
Thanks a lot !

**Comment by uvjim** [comment]
You mention using your wi-fi password. The password that you should be using is the one you would use to login to the local web interface for the primary node.

**Comment by Judediting** [comment]
> You mention using your wi-fi password. The password that you should be using is the one you would use to login to the local web interface for the primary node.

Thanks for the quick answer. :)

I know but the only way I have to connect locally it through https://www.linksyssmartwifi.com. If I try to use the ip address of the primary node to connect, it automatically redirects me to linksyssmartwifi.. :/ Do you have another way?

Thanks.

**Comment by uvjim** [comment]
I'm not sure which Velop model you have but you could try adding `/ca` after the IP address.

**Comment by Judediting** [comment]
I'm sorry I feel stupid I just forgot I had the main node password right below the router itself but I changed the admin password a while ago. So I updated it, and it works like a charm now. Thank you !

> I'm not sure which Velop model you have but you could try adding `/ca` after the IP address.

**Comment by uvjim** [comment]
No problem. Easily done.

When you set up the integration it should detect an incorrect password being used. I've tested multiple times with a bad password and it's been caught by the set-up routine.

I'll have to do some more tests to see if there's an edge case that gets through.

**Comment by Judediting** [comment]
> No problem. Easily done.
> 
> When you set up the integration it should detect an incorrect password being used. I've tested multiple times with a bad password and it's been caught by the set-up routine.
> 
> I'll have to do some more tests to see if there's an edge case that gets through.

This is why I didn't know what I was doing wrong because no matter the password I gave it went through all the installation process until the creation of some entities. But none of them was available.
On another website I read some posts from you telling what you've just said here above about catching incorrect password but it seems here it didn't work on my side.

Anyway, thank you again :)
