### ISSUE TITLE
Device Track - Always Home

### ISSUE THREAD

**Issue by Gr8z** [uvjim/linksys_velop#378]
The Device tracker isn't working as expected. I have set up my iPhone to be tracked but it always shows me home, no matter if I am connected or not.

Any Ideas?

![image](https://user-images.githubusercontent.com/4633243/214489786-f283b78f-5a50-40e4-97af-d0fdf731fffb.png)
![image](https://user-images.githubusercontent.com/4633243/214489815-0cd30cd9-b282-4c32-9f88-c5b11e2de278.png)

**Comment by uvjim** [comment]
Does the Linksys app show the iPhone as offline?

Have you waited long enough for the integration to mark the tracker as offline? A device tracker is only marked offline after the poll period (default 10s) sees the device offline and then starts the timer for `consider_home` (default 180s).

With these defaults you could have to wait up to 190s before being marked as offline.

I have 2 device trackers configured here and I'm not seeing an issue at present.

**Comment by Gr8z** [comment]
![image](https://user-images.githubusercontent.com/4633243/214655156-a9589112-e13d-4509-b6f3-d9df81b6299a.png)

Oh my bad, looks like i wasn't waiting long enough. It works!

Thank you

**Comment by uvjim** [comment]
No problem. You can reduce the consider home from 180s if you need it to happen quicker (you'll find that in the Timers section when you configure the integration). I've set it at that just to try and mitigate the drop and rejoin that mobile devices seem to do quite often.
