### ISSUE TITLE
Velop Cards don't work as it should.

### ISSUE THREAD

**Issue by Aekung** [uvjim/linksys_velop#379]
Hello,

I do have a problem with velop cards on card 2 and card 3. I'm not sure if there's a problem with the cards so you also decided to remove the card templates out from your readme file as well. However, I found that in your card 2, the binary sensor and the sensor entity will have velop_ in it while it actually doesn't have that in real entity's name. For example,

Your template is : binary_sensor.velop_mesh_wan_status
While the real entity is: binary_sensor.mesh_wan_status

Removing velop_ on all binary sensor and sensors does seem to partially fix Card 2, however, almost all the action button seem to be not working and throwing "mesh" key missing. 

For Card 3, nothing is working at all.

Do you know if there is the solution to this or should there be something that is missing in my setup and cause the problem?

Thank you and looking forward to your help.

**Comment by uvjim** [comment]
Hi, I've removed the cards from the README as you saw. They were only there as examples but I seemed to be getting a number of questions on them.  I have also moved away to using a different UI in Home Assistant so didn't see the need to maintain them.

You should be able to look at the documentation for the cards in use, i.e. `auto-entities`, `config-template-card` or `button-card` to get these working again for yourself.

**Comment by Aekung** [comment]
> Hi, I've removed the cards from the README as you saw. They were only there as examples but I seemed to be getting a number of questions on them. I have also moved away to using a different UI in Home Assistant so didn't see the need to maintain them.
> 
> You should be able to look at the documentation for the cards in use, i.e. `auto-entities`, `config-template-card` or `button-card` to get these working again for yourself.

Thank you for the reply. I have installed everything in order to use the velop cards but I will try checking each document once again tonight and see if I could make it work.

Anyway, thank you very much for all of your efforts creating this integration.

**Comment by uvjim** [comment]
> however, almost all the action button seem to be not working and throwing "mesh" key missing.

I think I fixed that for someone... have a look in #322 - there's a piece in there that uses `config-template-card` to ensure the Mesh ID is known.  I think the fix in #322 was for Card 3 but you should be able to apply similar to Card 2.

The `auto-entities` filter in Card 3 could probably be changed from

```yaml
- entity_id: /binary_sensor\..*_status/
      or:
        - attributes:
            guest_network: true
        - attributes:
            guest_network: false
```

to

```yaml
    - integration: linksys_velop
      entity_id: /binary_sensor\..*_status/
```

Also, for card 3, the backhaul attributes have been split into separate sensors so you'll need to adjust the code to cope with that.

**Comment by Aekung** [comment]
> > however, almost all the action button seem to be not working and throwing "mesh" key missing.
> 
> I think I fixed that for someone... have a look in #322 - there's a piece in there that uses `config-template-card` to ensure the Mesh ID is known. I think the fix in #322 was for Card 3 but you should be able to apply similar to Card 2.
> 
> The `auto-entities` filter in Card 3 could probably be changed from
> 
> ```yaml
> - entity_id: /binary_sensor\..*_status/
>       or:
>         - attributes:
>             guest_network: true
>         - attributes:
>             guest_network: false
> ```
> 
> to
> 
> ```yaml
>     - integration: linksys_velop
>       entity_id: /binary_sensor\..*_status/
> ```
> 
> Also, for card 3, the backhaul attributes have been split into separate sensors so you'll need to adjust the code to cope with that.

Really thank you for this, @uvjim . Now Card 3 seems to work as it should. I will try playing more with the backhaul and see if I could make it completely working.

Again, super thank you. Your work is amazing!

**Comment by Aekung** [comment]
Hello,

I think I could make all the features I want working already (though not completed but it should serve what I need now) Thank you very much for your help.

By the way, I wonder if there is anyway I could split card 3 into 2 column or section since I do have 7 nodes in my house and having all nodes list in one column means a never ending column so if I could split 4 nodes to another vertical grid it would be an ideal for me.

Can you please suggest if there is possibility for that since now nodes are auto populated in card 3 based on the number of node I actually have in the system and it's not manually configured so I can't just cut another 4 nodes to appear in another vertical grid.

Sorry for my English. I tried to explain what I want but I'm not so sure if it's understandable lol.

Thank you in advance.

**Comment by uvjim** [comment]
I'm not sure how your layout looks but you may want to investigate wrapping the card in something like [layout-card](https://github.com/thomasloven/lovelace-layout-card)

**Comment by mschingel** [comment]
However, I found that in your card 2, the binary sensor and the sensor entity will have velop_ in it while it actually doesn't have that in real entity's name. For example,
> 
> Your template is : binary_sensor.velop_mesh_wan_status While the real entity is: binary_sensor.mesh_wan_status
> 
> Removing velop_ on all binary sensor and sensors does seem to partially fix Card 2, however, almost all the action button seem to be not working and throwing "mesh" key missing.

Did you happen to fix the Device Card? The card that allows renaming, deleting of devices?

I am getting the mesh key error and couldn’t figure out how to fix it.

thank you
