### ISSUE TITLE
HA update broke cards

### ISSUE THREAD

**Issue by mschingel** [uvjim/linksys_velop#383]
Latest HA broke the cards with all the nodes. Only the primary node will show and the child nodes are no longer available. 

I didn’t test any other functions. Just wanted to report this. I restored a back up for now.

**Comment by uvjim** [comment]
I built a new interface using HA. It works well for me but as I went through it, it's quite complex to document and detail how to put it together so I haven't.

This [post](https://community.home-assistant.io/t/custom-integration-linksys-velop/342874/244) shows the UI.

**Comment by mschingel** [comment]
Looks like a nice design. If you ever document that please let me know.

In the meantime, if you could let me know where in the code I could begin
to troubleshoot the existing node card. I would appreciate it.

I appreciate your work and use it daily since velops mx4200 are
problematic. Using this integration combination with the cards to know the
status of nodes device counts etc have made it possible to ever tolerance
these routers.

Let me know. Thanks!

**Comment by uvjim** [comment]
You may want to change the `BUTTONS` variable to the following (note: not fully tested): -

```js
            () => {
              let ret = []
              let entity_prefix = "button." + "this.entity_id".split(".")[1].split("_").slice(0, -1).join("_")
              for (let entity_id in states) {
                if (entity_id.startsWith(entity_prefix) && states[entity_id] != undefined) {
                  let entity_action = states[entity_id].attributes.friendly_name.replace(vars['ROOM_NAME'], '').replace(/velop|:/gi, '').trim()
                  let device_id = this.hass.entities[entity_id].device_id
                  let config_entry_id = this.hass.devices[device_id].config_entries[0]
                  let mesh_object = Object.keys(this.hass.devices).filter(key => this.hass.devices[key].config_entries[0] == config_entry_id && this.hass.devices[key].model.startsWith("pyvelop"))
                  if (mesh_object) {
                    let entity_name = vars['ROOM_NAME']
                    ret.push({
                      'entity': entity_id,
                      'name': entity_action,
                      'tap_action': {
                          'action': 'call-service',
                          'service': 'linksys_velop.' + entity_action.toLowerCase() + '_node',
                          'service_data': {
                            'mesh': mesh_object[0],
                            'node_name': entity_name,
                          },
                          'confirmation': {
                            'text': 'Are you sure you want to reboot the ' + entity_name + ' node?'
                        }
                      }
                    })
                  }
                }
              }
              return ret
            }
```

**Comment by mschingel** [comment]
That worked! Thank you.

**Comment by mschingel** [comment]
How would I add the Data Service Mesh to the Device Details Card.
"Currently getting Failed to call service linksys_velop/delete_device.
required key not provided @ data['mesh']"

**Comment by uvjim** [comment]
```
linksys_velop_mesh:
    variables:
      mesh: |
        [[[
          if (entity) {
            let device_id = hass.entities[entity.entity_id].device_id
            let config_entry_id = hass.devices[device_id].config_entries[0]
            let mesh_device = Object.keys(hass.devices).filter(key => hass.devices[key].config_entries[0] == config_entry_id && hass.devices[key].model.startsWith("pyvelop"))
            if (mesh_device) {
              return mesh_device[0]
            }
          }
        ]]]
```

**Comment by mschingel** [comment]
That worked on for the Button Template.  For others, if it doesnt you can find you mesh information in the developers services, and select one of the velop services and look at the yaml it will be there.
