### ISSUE TITLE
Connection Error in Logs

### ISSUE THREAD

**Issue by TastePurple** [uvjim/linksys_velop#450]
**Frequently getting connection errors in the log but component appears to be functioning normally.** 

Logger: custom_components.linksys_velop
Source: helpers/update_coordinator.py:332
Integration: Linksys Velop (documentation, issues)
First occurred: February 17, 2024 at 10:42:08 PM (60 occurrences)
Last logged: 11:42:40 AM

Error fetching linksys_velop data: Connection Error

Logger: custom_components.linksys_velop
Source: custom_components/linksys_velop/__init__.py:326
Integration: Linksys Velop (documentation, issues)
First occurred: February 17, 2024 at 10:42:08 PM (61 occurrences)
Last logged: 11:42:40 AM

_async_get_mesh_data --> Connection Error

**Comment by uvjim** [comment]
Would you be a le to turn debug logging on please? That will hopefully give a better understanding of why the connection erroring.
