### ISSUE TITLE
Reboot primary node does not work

### ISSUE THREAD

**Issue by webwude** [uvjim/linksys_velop#459]
Hi.

I have defined an automation created, rebooting the whole mesh once every 12 days. 
I have four nodes. 

My sniplet for the automation looks like that:
`service: linksys_velop.reboot_node
metadata: {}
data:
  mesh: 0b0e1ea8f22f1199a5ab086aca65416b
  is_primary: true
  node_name: Velop Dach
`
Checking the log, I get the following entry:

Logger: custom_components.linksys_velop.service_handler
Quelle: custom_components/linksys_velop/service_handler.py:205
Integration: Linksys Velop (Dokumentation, Probleme)
Erstmals aufgetreten: 10:13:10 (5 Vorkommnisse)
Zuletzt protokolliert: 11:19:42

Velop Dach: no valid address found

Everything should be up to date. 
Thx for any hint.
Best regards
Michael

**Comment by PaRkThEcAr** [comment]
Hi! I was told to submit this as a new issue, but i see you have already done it. Here is my log entry as well. I have the MBE7000's on my network.

![image](https://github.com/uvjim/linksys_velop/assets/39027440/404b731d-222f-485e-8445-2e6b065761e7)

**Comment by uvjim** [comment]
These aren't going to work because the integration doesn't seem to have a valid address. Could you provide full debug logs please?

I don't have any of the same device to test with so I have no idea currently what it's returning via the API or how to handle it.

**Comment by webwude** [comment]
Hi.

Debug log attached.

[home-assistant_linksys_velop_2024-05-03T19-45-48.479Z.log](https://github.com/uvjim/linksys_velop/files/15204412/home-assistant_linksys_velop_2024-05-03T19-45-48.479Z.log)


> These aren't going to work because the integration doesn't seem to have a valid address. Could you provide full debug logs please?
> 
> I don't have any of the same device to test with so I have no idea currently what it's returning via the API or how to handle it.

**Comment by uvjim** [comment]
Thanks @webwude. Sorry to be a pain, could you also grab the file from the "Download Diagnostics" for the integration please?

The debug log shows all the calls being made I'd expect to see. I was hoping I'd logged all the responses. Either I have and they're truncated or I'm missing some of them in the logs (I'll look at that).

**Comment by webwude** [comment]
> Thanks @webwude. Sorry to be a pain, could you also grab the file from the "Download Diagnostics" for the integration please?
> 
> The debug log shows all the calls being made I'd expect to see. I was hoping I'd logged all the responses. Either I have and they're truncated or I'm missing some of them in the logs (I'll look at that).

here you go:

[config_entry-linksys_velop-793f6937c739dfac93fbce20e9ce009b.json](https://github.com/uvjim/linksys_velop/files/15204494/config_entry-linksys_velop-793f6937c739dfac93fbce20e9ce009b.json)

**Comment by uvjim** [comment]
Thanks @webwude. I can now see what's causing it. I'll try and get a fix provided this weekend.

**Comment by GSzabados** [comment]
@uvjim, it is partially belongs here. Could be a simple reboot button added for the mesh/primary node? 

I have to restart irregularly my whole setup, and doing it with a service call is rather cumbersome, as I never know what the entity or device called, as it not fetches it for the service and I never know how to set the primary switch there and so on. So it is always a trial and error first, and takes a few minutes. A single button would streamline this. Like a Whole Mesh Reboot under the primary node.

Thanks!

**Comment by uvjim** [comment]
> @uvjim, it is partially belongs here. Could be a simple reboot button added for the mesh/primary node? 
> 
> I have to restart irregularly my whole setup, and doing it with a service call is rather cumbersome, as I never know what the entity or device called, as it not fetches it for the service and I never know how to set the primary switch there and so on. So it is always a trial and error first, and takes a few minutes. A single button would streamline this. Like a Whole Mesh Reboot under the primary node.
> 
> Thanks!

Can you raise this as a separate feature request please? This has been asked a few times before and I'm not comfortable putting it as a button that will appear in the standard HASS UI. HASS does not prompt for confirmation and it would be too easy to accidentally restart the whole mesh when you didn't mean to.

I do have an idea of how I could expose it though so that it's down to the user to pay attention.

**Comment by GSzabados** [comment]
> I do have an idea of how I could expose it though so that it's down to the user to pay attention.

I will make a separate request. 

You could name it: `Reboot whole mesh system`!

**Comment by uvjim** [comment]
@webwude, @PaRkThEcAr - I believe I've now fixed this in the library.  I have a few more tests to do and then I'll update the integration to use the new library.

**Comment by uvjim** [comment]
@webwude, @PaRkThEcAr 

I've pushed a beta (`2024.5.1b0`) now.  Could you try this please and let me know if it resolves your issue please?  I'm not in a position to restart the mesh and don't currently have the test one set up.

**Comment by webwude** [comment]
> @webwude, @PaRkThEcAr
> 
> I've pushed a beta (`2024.5.1b0`) now. Could you try this and let me know if it resolves your issue please? I'm not in a position to restart the mesh and don't currently have the test one set up.

On it. Keep you posted. Thx for the update.

**Comment by webwude** [comment]
Looks good so far. Thank you.

**Comment by webwude** [comment]
Looks good so far. I guess it works.

**Comment by uvjim** [comment]
Brilliant. Thanks for testing.

**Comment by uvjim** [comment]
Fixed by #460
