### ISSUE TITLE
[Feature Request] Restart whole system button

### ISSUE THREAD

**Issue by GSzabados** [uvjim/linksys_velop#462]
Could be a simple reboot button added for the mesh/primary node?

I have to restart irregularly my whole setup, and doing it with a service call is rather cumbersome, as I never know what the entity or device called, as it not fetches it for the service and I never know how to set the primary switch there and so on. So it is always a trial and error first, and takes a few minutes. A single button would streamline this. Like a Whole Mesh Reboot under the primary node.

Thanks!

**Comment by GSzabados** [comment]
You could name it: Reboot whole mesh system!

**Comment by uvjim** [comment]
You'll be pleased to know that I pre-empted the request and checked in a solution earlier today.

I'll release another beta later today.

**Comment by GSzabados** [comment]
Thanks! I really appreciate it!

**Comment by uvjim** [comment]
Should be available in `2024.5.1b1` now.  You may want to check the README for how to enable it.

**Comment by GSzabados** [comment]
Thank you very much! It works flawlessly. Additionally I would update the readme on the top where it says it does not provide a button for this, saying as default, but you can enable it.

**Comment by uvjim** [comment]
I'll update that before release - completely forgot I'd put that statement in there. 😂

**Comment by GSzabados** [comment]
I see some new error message in the beta. I will open a new issue for that.

**Comment by uvjim** [comment]
Implemented in #461
