### ISSUE TITLE
WARNING StrEnum was used from linksys_velop

### ISSUE THREAD

**Issue by GSzabados** [uvjim/linksys_velop#464]
Some other warning which popped up recently. 

`2024-05-07 19:07:44.021 WARNING (ImportExecutor_0) [homeassistant.backports.enum] StrEnum was used from linksys_velop, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'linksys_velop' custom integration`

**Comment by uvjim** [comment]
Should be resolved by #465
