### ISSUE TITLE
Inconsistent connected devices 

### ISSUE THREAD

**Issue by gndenton** [uvjim/linksys_velop#474]
Hello.

I have built a simple dashboard to show various items about the home network. Here is a screenshot:
![Screenshot from 2024-07-19 15-36-13](https://github.com/user-attachments/assets/d6634fd1-cb81-451f-8c4b-59fae0a766fc)
 
As you can see, there 56 devices online, with a total of 39 connections on two APs.  Three of the APs do not have documented connections (one is an extender, which probably explains the lack of connections).
This is not a big issue, so don't feel the need for a rapid reply.

1. How do we get the count of connected devices "equal" to the number of Online Devices?
2. How are wired connections addressed? Are they included in the connections count?

Thanks!
Gary

**Comment by uvjim** [comment]
Hopefully these answer your queries...


1. https://github.com/uvjim/linksys_velop/issues/58
2. https://github.com/uvjim/linksys_velop#sensors - check the attributes of the `Mesh: Number of Online Devices` or `Node: Number of Connected Devices` depending on where you want the information from.

**Comment by uvjim** [comment]
@gndenton have these evened out now?

**Comment by gndenton** [comment]
No.  There continues to be a delta of approximately 10.

Gary


Gary N. Denton
Mobile: +1 (317) 430-3051
Email: ***@***.***

________________________________

**Comment by uvjim** [comment]
So, in the Linksys app do you see something like this?

![Screenshot_20240808_144448_Linksys.png](https://github.com/user-attachments/assets/83523639-4d8a-4c27-8de2-1a23720ba56d)

Notice that some of the devices have a double dash where you'd expect to see the node name. In my experience these are the ones which cause the discrepancy. The number of online devices on the mesh is correct (as is the number of offline devices on the mesh). The node counts are also correct, but those with the dashes don't identify which node they are on so can't be included in a count.

My experience shows that this slowly corrects itself over time, or a reboot (or network refresh) of the device (not node or mesh) will cause it to identify the node it is connected to again.

**Comment by gndenton** [comment]
Yes - I see a similar pattern. The three dots (two dashes, as your file shows) seem to be the devices which are hardwired to the AP (via a switch where multiple devices exist). At this point, I'll continue to monitor the numbers and look for a decreasing delta.

I would be okay with closing the issue.



Gary N. Denton
Mobile: +1 (317) 430-3051
Email: ***@***.***

________________________________
