### ISSUE TITLE
The [name] node is no longer on the Mesh or it's unique ID has changed.

### ISSUE THREAD

**Issue by gndenton** [uvjim/linksys_velop#495]
After updating to version 2024.10.2, I had 3 nodes out of 5 nodes reporting an error with the next step being removal of those nodes from Home Assistant. My primary nodes was not listed.

What are my next steps after removing the nodes to return to "normal".

Thank you in advance.

**Comment by uvjim** [comment]
Try reloading the integration. If the API is still reporting the nodes they should be recreated as devices in Home Assistant.

**Comment by gndenton** [comment]
Thank you for the quick response.

I deleted one of the nodes and when I try to re-add it to the system, I get a pop-up asking for primary node IP address, and password, but no ID request.  The action fails since there is no ID being entered or submitted to Linksys.

Thanks again,
Gary

Gary N. Denton
Mobile: +1 (317) 430-3051
Email: ***@***.***

________________________________

**Comment by uvjim** [comment]
You shouldn't need to enter a username because it users the router password which has a well known username. It sounds like you're attempting to use the cloud account details, which you shouldn't be using.

**Comment by gndenton** [comment]
yes - I am embarrassed to say you are correct.  Once I tried the local password, I tried to add a device.  There were no other input questions, but there is a completion pop-up stating "Device already configured".

Again, my apologies.


Gary N. Denton
Mobile: +1 (317) 430-3051
Email: ***@***.***

________________________________

**Comment by uvjim** [comment]
Yes, if it's already configured it will say that. Rather than re-add (which would involve removing the integration and adding it again) you should be able to just tell it to reload. If a reload doesn't create the devices for the nodes, and the Linksys app shows the nodes as being online, then you'd be best to remove and add it again.

**Comment by gndenton** [comment]
That worked.  It was a case of PEBKAC (problem exists between keyboard and chair).

Thanks.  Okay to close.

Gary N. Denton
Mobile: +1 (317) 430-3051
Email: ***@***.***

________________________________
