### ISSUE TITLE
Router Connected Devices do not add up to  Online Devices Online Device  

### ISSUE THREAD

**Issue by ddyeakley** [uvjim/linksys_velop#58]
Router Connected Devices do not add up to  Online Devices Online Device.   Show 33 Online Devices but only 25 connected devices.   Logs attached.

![image](https://user-images.githubusercontent.com/680167/149810846-7f4fa5fb-4fe0-44ec-8d58-6140f97b4e5f.png)

[home-assistant.log](https://github.com/uvjim/linksys_velop/files/7883640/home-assistant.log)

**Comment by ddyeakley** [comment]
I thought it was related to devices with unknown type (wifi, ethernet, unknown).    However I only see one unknown type, maybe there is parsing that fails on the first known type?

**Comment by uvjim** [comment]
Yup.  I actually mentioned this recently in the thread on the HASS community.  Give it time and they eventually come back in line.

The two smaller numbers that add up to 25 are those that I can identify a parent node in.  In your scenario there 8 devices which I cannot identify a parent node for.  It doesn't mean that they're not connected, just that I don't know where.  The info just doesn't come back in the API response for me to make the decision.

I will have a look at the response in your log though just in case their is something in your environment where I could make the decision.

As I say though, in my environment, given time, they actually do come in line.  It can however, take hours, days weeks before it does.

**Comment by uvjim** [comment]
I've had a quick look at the log and it seems to tally up.  There are 9 devices showing as having no `parentDeviceID` in the device list.  1 of those will be the primary node, the other 8 tallies up with the 8 missing in the counts you highlighted.

**Comment by ddyeakley** [comment]
I understand.   Thank you for taking a look.
