### ISSUE TITLE
Card type???? 

### ISSUE THREAD

**Issue by Diegoloex** [uvjim/linksys_velop#97]

**Comment by Diegoloex** [comment]
I feel my question is so short and cryptic, but my English is something more than horrible. I write to you through google translate. sorry for possible errors. You have an example on your github of the card you use, and I love it. When copying the code, it gives me an error that the type of card is missing. I have deleted the path line and set it as vertical stack type and it works halfway, it gives me that it is not right that way. Thank you very much for your time and work, it is really an incredible and functional integration, much better than the native app in my opinion.  Enviado desde Correo para Windows De: uvjimEnviado: viernes, 18 de febrero de 2022 18:53Para: uvjim/linksys_velopCC: Diegoloex; AuthorAsunto: Re: [uvjim/linksys_velop] Card type???? (Issue #97) I'm not sure I understand what you're asking? This is an integration. What are you attempting to do?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by uvjim** [comment]
No problem at all.

Does this post in the Home Assistant forum help?

https://community.home-assistant.io/t/custom-integration-linksys-velop/342874/21

There's been a few updates to the cards since then mind you but this should get you up and running.

If that works, I'll look at splitting the view up in the README into sections like that post.

I'm also assuming that you have all of the pre-requisite custom cards installed as per the README.

Let me know how you get on.

**Comment by uvjim** [comment]
Hi,

Your last comment was against a PR I recently merged. Was there a screenshot?

It didn't come in with the comment. Could you reply using the GitHub website rather than email as you should be able to paste a screenshot of the issue in there.

Thanks.

**Comment by Diegoloex** [comment]
I'm really sorry, honestly. I've been a couple of weeks... off, to be mild when I say it.

I'm trying all your changes right now and... wow, yours often worked.

In principle, everything seems correct and almost everything works for me without making any changes to the yaml. Only the reebot button fails me, but because I have the wrong credentials, it tells me. Then I'll take a while and take a good look to see what the fault is.

a thousand apologies again, and thank you very much for your time, work, effort... truly, thank you very much.

where is the button to invite you to a coffee??

**Comment by uvjim** [comment]
Thanks for the update. I'll close this off now.
I have no link for donations. Thank you for the offer though.
